name: petro-weekly

on:
  schedule:
    - cron: '0 1 * * 1'  # 每周一 01:00 UTC（台北 09:00）
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate weekly log
        run: |
          python scripts/fetch_prices.py

      - name: Commit & Push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add logs/*.md data/history.jsonl
          git commit -m "chore(log): weekly petro prices $(date -u +'%Y-%m-%d')" || echo "No changes"
          git push
